services:

  # ─── Base de Datos MySQL ───────────────────────────────────────────
  mysql:
    image: mysql:8.0
    container_name: mysql-spring-security
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 753159852
      MYSQL_DATABASE: bd_app
    ports:
      - "3307:3306"   # Puerto 3307 en tu máquina → 3306 en el contenedor
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-data:
