spring.application.name=app-tutorial-spring-security
# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3307/db-1
spring.datasource.username=root
spring.datasource.password=example
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Configuración de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#seguridad
security.jwt.secret-key=2925a5ed1071cf153c72de81c326bf721bb59953bcae91b84fa5d12f94b56c35
jwt.expiration=70000